// ======================================
// Auto Journal Entry System - نظام القيود المحاسبية التلقائية
// تسجيل القيود المحاسبية تلقائياً لجميع العمليات
// ======================================

/**
 * هذا النظام يربط جميع العمليات التجارية بالقيود المحاسبية تلقائياً:
 * - المبيعات → قيد المبيعات + تكلفة المبيعات
 * - المشتريات → قيد المشتريات
 * - الرواتب → قيد المصروفات
 * - الإنتاج → قيد التكاليف الصناعية
 * - الإهلاك → قيد الإهلاك
 * - الخ...
 */

import { dbManager, STORES } from '../../database/IndexedDBManager';

// معرفات الحسابات الافتراضية (يمكن تخصيصها)
const DEFAULT_ACCOUNTS = {
  // الأصول
  CASH: 101,                    // النقدية
  ACCOUNTS_RECEIVABLE: 102,     // العملاء (المدينون)
  INVENTORY: 103,               // المخزون
  FIXED_ASSETS: 104,            // الأصول الثابتة
  ACCUMULATED_DEPRECIATION: 105, // مجمع الإهلاك
  
  // الخصوم
  ACCOUNTS_PAYABLE: 201,        // الموردون (الدائنون)
  SALARIES_PAYABLE: 202,        // الرواتب المستحقة
  TAXES_PAYABLE: 203,           // الضرائب المستحقة
  
  // حقوق الملكية
  CAPITAL: 301,                 // رأس المال
  RETAINED_EARNINGS: 302,       // الأرباح المحتجزة
  
  // الإيرادات
  SALES_REVENUE: 401,           // إيرادات المبيعات
  OTHER_REVENUE: 402,           // إيرادات أخرى
  
  // تكلفة المبيعات
  COST_OF_GOODS_SOLD: 501,      // تكلفة البضاعة المباعة
  
  // المصروفات
  SALARIES_EXPENSE: 601,        // مصروف الرواتب
  RENT_EXPENSE: 602,            // مصروف الإيجار
  UTILITIES_EXPENSE: 603,       // مصروف المرافق
  DEPRECIATION_EXPENSE: 604,    // مصروف الإهلاك
  MAINTENANCE_EXPENSE: 605,     // مصروف الصيانة
  PRODUCTION_OVERHEAD: 606,     // تكاليف صناعية غير مباشرة
  
  // حسابات خاصة
  PURCHASE_DISCOUNT: 701,       // خصم المشتريات
  SALES_DISCOUNT: 702,          // خصم المبيعات
  PURCHASE_RETURNS: 703,        // مرتجعات المشتريات
  SALES_RETURNS: 704            // مرتجعات المبيعات
};

class AutoJournalEntry {
  constructor() {
    this.accounts = DEFAULT_ACCOUNTS;
  }

  /**
   * إنشاء قيد محاسبي تلقائي
   */
  async createEntry(entryData) {
    const { date, description, reference, entries } = entryData;
    
    // التحقق من توازن القيد
    const totalDebit = entries.reduce((sum, e) => sum + (e.debit || 0), 0);
    const totalCredit = entries.reduce((sum, e) => sum + (e.credit || 0), 0);
    
    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      throw new Error(
        `القيد غير متوازن: المدين = ${totalDebit.toFixed(2)}, الدائن = ${totalCredit.toFixed(2)}`
      );
    }

    // إنشاء رقم تسلسلي
    const allEntries = await dbManager.getAll(STORES.journalEntries);
    const nextNumber = allEntries.length > 0 
      ? Math.max(...allEntries.map(e => e.entryNumber || 0)) + 1 
      : 1;

    const newEntry = {
      id: Date.now(),
      entryNumber: nextNumber,
      date: date || new Date().toISOString(),
      description,
      reference,
      entries: entries.map(e => ({
        ...e,
        id: Date.now() + Math.random()
      })),
      totalDebit,
      totalCredit,
      status: 'posted',
      autoGenerated: true,
      createdAt: new Date().toISOString(),
      postedAt: new Date().toISOString()
    };

    // حفظ القيد
    await dbManager.add(STORES.journalEntries, newEntry);

    // تحديث أرصدة الحسابات
    await this._updateAccountBalances(entries);

    return newEntry;
  }

  /**
   * تحديث أرصدة الحسابات
   */
  async _updateAccountBalances(entryLines) {
    for (const line of entryLines) {
      const account = await dbManager.get(STORES.accounts, line.accountId);
      
      if (!account) {
        console.warn(`الحساب ${line.accountId} غير موجود`);
        continue;
      }

      let currentBalance = account.balance || 0;
      
      // حساب الرصيد الجديد حسب طبيعة الحساب
      if (line.debit && line.debit > 0) {
        if (account.nature === 'debit') {
          currentBalance += line.debit;
        } else {
          currentBalance -= line.debit;
        }
      }
      
      if (line.credit && line.credit > 0) {
        if (account.nature === 'credit') {
          currentBalance += line.credit;
        } else {
          currentBalance -= line.credit;
        }
      }

      // تحديث الحساب
      await dbManager.update(STORES.accounts, {
        ...account,
        balance: currentBalance,
        updatedAt: new Date().toISOString()
      });
    }
  }

  // ==================== قيود المبيعات ====================

  /**
   * قيد فاتورة مبيعات نقدية
   */
  async createSalesCashEntry(invoice) {
    const entries = [
      // مدين: النقدية
      {
        accountId: this.accounts.CASH,
        accountName: 'النقدية',
        debit: invoice.total,
        credit: 0,
        description: `مبيعات نقدية - فاتورة ${invoice.id}`
      },
      // دائن: المبيعات
      {
        accountId: this.accounts.SALES_REVENUE,
        accountName: 'إيرادات المبيعات',
        debit: 0,
        credit: invoice.total,
        description: `مبيعات نقدية - فاتورة ${invoice.id}`
      }
    ];

    // إذا كان هناك خصم
    if (invoice.discountAmount && invoice.discountAmount > 0) {
      entries[1].credit = invoice.total + invoice.discountAmount;
      entries.push({
        accountId: this.accounts.SALES_DISCOUNT,
        accountName: 'خصم المبيعات',
        debit: invoice.discountAmount,
        credit: 0,
        description: `خصم على فاتورة ${invoice.id}`
      });
    }

    return await this.createEntry({
      date: invoice.date,
      description: `مبيعات نقدية - عميل: ${invoice.customerName || 'عميل نقدي'}`,
      reference: `SAL-${invoice.id}`,
      entries
    });
  }

  /**
   * قيد فاتورة مبيعات آجلة
   */
  async createSalesCreditEntry(invoice) {
    const entries = [
      // مدين: العملاء (المدينون)
      {
        accountId: this.accounts.ACCOUNTS_RECEIVABLE,
        accountName: 'العملاء',
        debit: invoice.total,
        credit: 0,
        description: `مبيعات آجلة - فاتورة ${invoice.id}`,
        customerId: invoice.customerId
      },
      // دائن: المبيعات
      {
        accountId: this.accounts.SALES_REVENUE,
        accountName: 'إيرادات المبيعات',
        debit: 0,
        credit: invoice.total,
        description: `مبيعات آجلة - فاتورة ${invoice.id}`
      }
    ];

    return await this.createEntry({
      date: invoice.date,
      description: `مبيعات آجلة - عميل: ${invoice.customerName}`,
      reference: `SAL-${invoice.id}`,
      entries
    });
  }

  /**
   * قيد تكلفة البضاعة المباعة
   */
  async createCOGSEntry(invoice, costOfGoods) {
    const entries = [
      // مدين: تكلفة البضاعة المباعة
      {
        accountId: this.accounts.COST_OF_GOODS_SOLD,
        accountName: 'تكلفة البضاعة المباعة',
        debit: costOfGoods,
        credit: 0,
        description: `تكلفة المبيعات - فاتورة ${invoice.id}`
      },
      // دائن: المخزون
      {
        accountId: this.accounts.INVENTORY,
        accountName: 'المخزون',
        debit: 0,
        credit: costOfGoods,
        description: `تكلفة المبيعات - فاتورة ${invoice.id}`
      }
    ];

    return await this.createEntry({
      date: invoice.date,
      description: `تكلفة البضاعة المباعة - فاتورة ${invoice.id}`,
      reference: `COGS-${invoice.id}`,
      entries
    });
  }

  // ==================== قيود المشتريات ====================

  /**
   * قيد فاتورة مشتريات نقدية
   */
  async createPurchaseCashEntry(invoice) {
    const entries = [
      // مدين: المخزون
      {
        accountId: this.accounts.INVENTORY,
        accountName: 'المخزون',
        debit: invoice.total,
        credit: 0,
        description: `مشتريات نقدية - فاتورة ${invoice.id}`
      },
      // دائن: النقدية
      {
        accountId: this.accounts.CASH,
        accountName: 'النقدية',
        debit: 0,
        credit: invoice.total,
        description: `مشتريات نقدية - فاتورة ${invoice.id}`
      }
    ];

    return await this.createEntry({
      date: invoice.date,
      description: `مشتريات نقدية - مورد: ${invoice.supplierName || 'مورد'}`,
      reference: `PUR-${invoice.id}`,
      entries
    });
  }

  /**
   * قيد فاتورة مشتريات آجلة
   */
  async createPurchaseCreditEntry(invoice) {
    const entries = [
      // مدين: المخزون
      {
        accountId: this.accounts.INVENTORY,
        accountName: 'المخزون',
        debit: invoice.total,
        credit: 0,
        description: `مشتريات آجلة - فاتورة ${invoice.id}`
      },
      // دائن: الموردون (الدائنون)
      {
        accountId: this.accounts.ACCOUNTS_PAYABLE,
        accountName: 'الموردون',
        debit: 0,
        credit: invoice.total,
        description: `مشتريات آجلة - فاتورة ${invoice.id}`,
        supplierId: invoice.supplierId
      }
    ];

    return await this.createEntry({
      date: invoice.date,
      description: `مشتريات آجلة - مورد: ${invoice.supplierName}`,
      reference: `PUR-${invoice.id}`,
      entries
    });
  }

  // ==================== قيود المرتجعات ====================

  /**
   * قيد مرتجع مبيعات
   */
  async createSalesReturnEntry(salesReturn, invoice) {
    const entries = [];

    if (invoice.paymentType === 'cash') {
      // عكس قيد المبيعات النقدية
      entries.push(
        {
          accountId: this.accounts.SALES_REVENUE,
          accountName: 'إيرادات المبيعات',
          debit: salesReturn.totalAmount,
          credit: 0,
          description: `مرتجع مبيعات - فاتورة ${invoice.id}`
        },
        {
          accountId: this.accounts.CASH,
          accountName: 'النقدية',
          debit: 0,
          credit: salesReturn.totalAmount,
          description: `مرتجع مبيعات - فاتورة ${invoice.id}`
        }
      );
    } else {
      // عكس قيد المبيعات الآجلة
      entries.push(
        {
          accountId: this.accounts.SALES_REVENUE,
          accountName: 'إيرادات المبيعات',
          debit: salesReturn.totalAmount,
          credit: 0,
          description: `مرتجع مبيعات - فاتورة ${invoice.id}`
        },
        {
          accountId: this.accounts.ACCOUNTS_RECEIVABLE,
          accountName: 'العملاء',
          debit: 0,
          credit: salesReturn.totalAmount,
          description: `مرتجع مبيعات - فاتورة ${invoice.id}`,
          customerId: invoice.customerId
        }
      );
    }

    return await this.createEntry({
      date: salesReturn.date,
      description: `مرتجع مبيعات - فاتورة ${invoice.id}`,
      reference: `SRET-${salesReturn.id}`,
      entries
    });
  }

  /**
   * قيد مرتجع مشتريات
   */
  async createPurchaseReturnEntry(purchaseReturn, invoice) {
    const entries = [];

    if (invoice.paymentType === 'cash') {
      // عكس قيد المشتريات النقدية
      entries.push(
        {
          accountId: this.accounts.CASH,
          accountName: 'النقدية',
          debit: purchaseReturn.totalAmount,
          credit: 0,
          description: `مرتجع مشتريات - فاتورة ${invoice.id}`
        },
        {
          accountId: this.accounts.INVENTORY,
          accountName: 'المخزون',
          debit: 0,
          credit: purchaseReturn.totalAmount,
          description: `مرتجع مشتريات - فاتورة ${invoice.id}`
        }
      );
    } else {
      // عكس قيد المشتريات الآجلة
      entries.push(
        {
          accountId: this.accounts.ACCOUNTS_PAYABLE,
          accountName: 'الموردون',
          debit: purchaseReturn.totalAmount,
          credit: 0,
          description: `مرتجع مشتريات - فاتورة ${invoice.id}`,
          supplierId: invoice.supplierId
        },
        {
          accountId: this.accounts.INVENTORY,
          accountName: 'المخزون',
          debit: 0,
          credit: purchaseReturn.totalAmount,
          description: `مرتجع مشتريات - فاتورة ${invoice.id}`
        }
      );
    }

    return await this.createEntry({
      date: purchaseReturn.date,
      description: `مرتجع مشتريات - فاتورة ${invoice.id}`,
      reference: `PRET-${purchaseReturn.id}`,
      entries
    });
  }

  // ==================== قيود الرواتب ====================

  /**
   * قيد صرف الرواتب
   */
  async createPayrollEntry(payrollData) {
    const entries = [
      // مدين: مصروف الرواتب
      {
        accountId: this.accounts.SALARIES_EXPENSE,
        accountName: 'مصروف الرواتب',
        debit: payrollData.totalNetSalary,
        credit: 0,
        description: `رواتب ${payrollData.periodName || 'الشهر'}`
      },
      // دائن: النقدية
      {
        accountId: this.accounts.CASH,
        accountName: 'النقدية',
        debit: 0,
        credit: payrollData.totalNetSalary,
        description: `صرف رواتب ${payrollData.periodName || 'الشهر'}`
      }
    ];

    return await this.createEntry({
      date: payrollData.date || new Date().toISOString(),
      description: `صرف رواتب ${payrollData.periodName || 'الشهر'}`,
      reference: `PAY-${payrollData.periodId}`,
      entries
    });
  }

  // ==================== قيود الإهلاك ====================

  /**
   * قيد الإهلاك
   */
  async createDepreciationEntry(depreciationData) {
    const entries = [
      // مدين: مصروف الإهلاك
      {
        accountId: this.accounts.DEPRECIATION_EXPENSE,
        accountName: 'مصروف الإهلاك',
        debit: depreciationData.depreciationAmount,
        credit: 0,
        description: `إهلاك ${depreciationData.assetName} - ${depreciationData.period}`
      },
      // دائن: مجمع الإهلاك
      {
        accountId: this.accounts.ACCUMULATED_DEPRECIATION,
        accountName: 'مجمع الإهلاك',
        debit: 0,
        credit: depreciationData.depreciationAmount,
        description: `إهلاك ${depreciationData.assetName} - ${depreciationData.period}`
      }
    ];

    return await this.createEntry({
      date: depreciationData.date || new Date().toISOString(),
      description: `إهلاك ${depreciationData.assetName}`,
      reference: `DEP-${depreciationData.assetId}-${depreciationData.period}`,
      entries
    });
  }

  // ==================== قيود الإنتاج ====================

  /**
   * قيد استهلاك المواد الخام
   */
  async createMaterialConsumptionEntry(productionOrder, materials) {
    const totalCost = materials.reduce((sum, m) => sum + m.cost, 0);

    const entries = [
      // مدين: تكاليف صناعية
      {
        accountId: this.accounts.PRODUCTION_OVERHEAD,
        accountName: 'تكاليف صناعية',
        debit: totalCost,
        credit: 0,
        description: `استهلاك مواد - أمر إنتاج ${productionOrder.id}`
      },
      // دائن: المخزون
      {
        accountId: this.accounts.INVENTORY,
        accountName: 'المخزون',
        debit: 0,
        credit: totalCost,
        description: `استهلاك مواد - أمر إنتاج ${productionOrder.id}`
      }
    ];

    return await this.createEntry({
      date: productionOrder.actualStartDate || new Date().toISOString(),
      description: `استهلاك مواد خام - أمر إنتاج ${productionOrder.id}`,
      reference: `PROD-MAT-${productionOrder.id}`,
      entries
    });
  }

  /**
   * قيد إتمام الإنتاج
   */
  async createProductionCompletionEntry(productionOrder, productionCost) {
    const entries = [
      // مدين: المخزون (منتجات تامة)
      {
        accountId: this.accounts.INVENTORY,
        accountName: 'المخزون - منتجات تامة',
        debit: productionCost,
        credit: 0,
        description: `إتمام إنتاج - أمر ${productionOrder.id}`
      },
      // دائن: تكاليف صناعية
      {
        accountId: this.accounts.PRODUCTION_OVERHEAD,
        accountName: 'تكاليف صناعية',
        debit: 0,
        credit: productionCost,
        description: `إتمام إنتاج - أمر ${productionOrder.id}`
      }
    ];

    return await this.createEntry({
      date: productionOrder.actualEndDate || new Date().toISOString(),
      description: `إتمام أمر إنتاج ${productionOrder.id}`,
      reference: `PROD-COMP-${productionOrder.id}`,
      entries
    });
  }

  // ==================== دوال مساعدة ====================

  /**
   * حساب تكلفة المبيعات (COGS)
   */
  async calculateCOGS(invoice) {
    let totalCost = 0;

    for (const item of invoice.items) {
      const product = await dbManager.get(STORES.products, item.productId);
      
      if (product) {
        // تكلفة الوحدة الأساسية
        const mainCost = (item.quantity || 0) * (product.costPrice || 0);
        // تكلفة الوحدة الفرعية
        const subCost = (item.subQuantity || 0) * (product.subCostPrice || product.costPrice / (product.unitsInMain || 1));
        
        totalCost += mainCost + subCost;
      }
    }

    return totalCost;
  }

  /**
   * حفظ القيد مع المعاملة
   */
  async createSalesJournalEntries(invoice) {
    try {
      // قيد المبيعات
      if (invoice.paymentType === 'cash') {
        await this.createSalesCashEntry(invoice);
      } else {
        await this.createSalesCreditEntry(invoice);
      }

      // قيد تكلفة المبيعات
      const cogs = await this.calculateCOGS(invoice);
      if (cogs > 0) {
        await this.createCOGSEntry(invoice, cogs);
      }

      return true;
    } catch (error) {
      console.error('خطأ في إنشاء قيود المبيعات:', error);
      throw error;
    }
  }

  /**
   * حفظ قيود المشتريات
   */
  async createPurchaseJournalEntries(invoice) {
    try {
      if (invoice.paymentType === 'cash') {
        await this.createPurchaseCashEntry(invoice);
      } else {
        await this.createPurchaseCreditEntry(invoice);
      }

      return true;
    } catch (error) {
      console.error('خطأ في إنشاء قيود المشتريات:', error);
      throw error;
    }
  }
}

// إنشاء نسخة singleton
const autoJournalEntry = new AutoJournalEntry();

export { autoJournalEntry, DEFAULT_ACCOUNTS };
export default AutoJournalEntry;
